[package]
name = "stable_identifier"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"], optional = true }
nanoid = "0.4.0"

[features]
serde = ["dep:serde"]
